import Head from "next/head";
import Bar from "../components/bar/bar";
import BlockFooter from "../components/block-footer/block-footer";
import BlockFunctionalities from "../components/block-functionalities/block-functionalities";
import BlockHow from "../components/block-how/block-how";
import BlockTop from "../components/block-top/block-top";
import Cover from "../components/cover/cover";
import HR from "../components/hr/hr";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bar />

      <Cover />
      <HR />
      <BlockFunctionalities />
      <HR />
      <BlockHow />
      <HR />
      <BlockTop />
      <HR />
      <BlockFooter />
    </div>
  );
}
